### PR TITLE
Make variables user-settable

### PR DESCRIPTION
**Pull request by DoomHammer**
Not everyone wants to have a tmux indicator. Since it is already set in a variable, this PR makes it possible to override by users.

### CODE REVIEW

**Comment by miekg** [comment]
Also should add some docs about this in the README

**Comment by DoomHammer** [comment]
Funniest thing is it ceased working as advertised after I started a new shell. Will have to work a bit on it, I guess.

**Comment by miekg** [comment]
What, that doesn't make sense

**Comment by DoomHammer** [comment]
I already know that. Tell this to my `zsh` :/

**Comment by DoomHammer** [comment]
OK, one other possible explanation is just me being stupid and unable to use `zgen` properly. Will let you know when I investigate more.

Also: thanks for the very nice prompt!

**Comment by DoomHammer** [comment]
Yes, the explanation is my stupidity. I was setting the variable after it was used. Will fix the docs soon.

**Comment by DoomHammer** [comment]
And they are in #7.

**Pull request merged**
