### PR TITLE
Term title: unset under Emacs

### PR DESCRIPTION
**Pull request by YujiShen**
I referenced pure theme for how to deal with title under Emacs, and create a function for setting title. Related issue #34.

### CODE REVIEW

**Comment by miekg** [comment]
this should probably be generalized; i.e. `PROMPT_LEAN_NOTITLE` as a var; which when set will not draw a title. Needs README update as well.

**Comment by YujiShen** [comment]
Thanks for suggestion! I am not very familiar with shell script, but I try my best. Please review my new commit.

**Comment by miekg** [comment]
This should drop any references to EMACS and emacs. I don't want to merge code that leads to maintaining a list of editors and other things that need to be checked.

**Comment by miekg** [comment]
yep thanks

**Comment by YujiShen** [comment]
Thanks! First PR on GitHub! 🎉

**Comment by miekg** [comment]
congrats, welcome to open source! :)

**Pull request merged**
